/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  homeSidebar: [{ type: 'autogenerated', dirName: 'home' }],
  developSidebar: [
    'develop/index',
    'develop/roadmap',
    {
      type: 'category',
      collapsed: true,
      label: 'Mockup',
      items: [
        'develop/mockup/design',
        'develop/mockup/customer-feedback',
        'develop/mockup/entrepreneur-feedback',
        'develop/mockup/chatgpt-feedback',
      ],
    },
    {
      type: 'category',
      label: 'Alpha Release',
      collapsed: true,
      items: [
        'develop/alpha-release/onboarding',
        'develop/alpha-release/installation',
        'develop/alpha-release/requirements',
        'develop/alpha-release/data-model',
        'develop/alpha-release/architecture',
        'develop/alpha-release/scripts',
      ],
    },],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
